# -*- coding: utf-8 -*-
"""
Created on Sat Aug 31 07:22:12 2024

"""

import json

#tile size is 16, so that is why Im using 16
item_data = {
            1: {
                'item_name': 'Log',
                'img_coords': (16 * 3, 16 * 3, 16 * 3, 16 * 3),
                'stackable': True,
                'damage': 0,
                'destroy_type': 'None',
                'protection': 0,
                'throwable': False,
                },
            2: {
                'item_name': 'Stick',
                'img_coords': (16 * 3, 0, 16 * 3, 16 * 3),
                'stackable': True,
                'damage': 0,
                'destroy_type': 'None',
                'protection': 0,
                'throwable': False,
                },
            3: {
                'item_name': 'Wooden Planks',
                'img_coords': (16 * 3 + 2, 36 * 3 - 12, 16 * 3, 16 * 3),
                'stackable': True,
                'damage': 0,
                'destroy_type': 'None',
                'protection': 0,
                'throwable': False,
                },
            4: {
                'item_name': 'Rock',
                'img_coords': (0, 16 * 3, 16 * 3, 16 * 3),
                'stackable': True,
                'damage': 0,
                'destroy_type': 'None',
                'protection': 0,
                'throwable': False,
                },
            5: {
                'item_name': 'Cobblestone',
                'img_coords': (0, 0, 16 * 3, 16 * 3),
                'stackable': True,
                'damage': 0,
                'destroy_type': 'None',
                'protection': 0,
                'throwable': False,
                },
            6: {
                'item_name': 'Log',
                'img_coords': (16 * 3, 16 * 3, 16 * 3, 16 * 3),
                'stackable': True,
                'damage': 0,
                'destroy_type': 'None',
                'protection': 0,
                'throwable': False,
                },
            7: {
                'item_name': 'Sharp Stick',
                'img_coords': (16 * 2 * 3, 16 * 2 * 3, 16 * 3, 16 * 3),
                'stackable': False,
                'damage': 1,
                'destroy_type': 'wood',
                'protection': 0,
                'throwable': False,
                },
            8: {
                'item_name': 'Wooden Axe',
                'img_coords': (16 * 2 * 3 + 7, 0, 16 * 3, 16 * 3),
                'stackable': False,
                'damage': 2,
                'destroy_type': 'wood',
                'protection': 0,
                'throwable': False,
                },
            9: {
                'item_name': 'Wooden Pickaxe',
                'img_coords': (16 * 2 * 3 + 4, 16 * 3 - 4, 16 * 3, 16 * 3),
                'stackable': False,
                'damage': 1,
                'destroy_type': 'Stone',
                'protection': 0,
                'throwable': False,
                },
            10: {
                'item_name': 'Sharp Stone',
                'img_coords': (16 * 3 * 3, 16 * 2 * 3, 16 * 3, 16 * 3),
                'stackable': True,
                'damage': 1,
                'destroy_type': 'Stone',
                'protection': 0,
                'throwable': False,
                },
            11: {
                'item_name': 'Stone Axe',
                'img_coords': (16 * 3 * 3 + 6, 0, 16 * 3, 16 * 3),
                'stackable': False,
                'damage': 3,
                'destroy_type': 'wood',
                'protection': 0,
                'throwable': False,
                },
            12: {
                'item_name': 'Stone Pickaxe',
                'img_coords': (16 * 3 * 3 + 4, 16 * 3 - 4, 16 * 3, 16 * 3),
                'stackable': False,
                'damage': 2,
                'destroy_type': 'Stone',
                'protection': 0,
                'throwable': False,
                },
            13: {
                'item_name': 'Sugar String',
                'img_coords': (16 * 4 * 3, 0, 16 * 3, 16 * 3),
                'stackable': True,
                'damage': 0,
                'destroy_type': 'None',
                'protection': 0,
                'throwable': False,
                },
            14: {
                'item_name': 'Sugar Cloth',
                'img_coords': (16 * 4 * 3, 16 * 3, 16 * 3, 16 * 3),
                'stackable': True,
                'damage': 0,
                'destroy_type': 'None',
                'protection': 0,
                'throwable': False,
                },
            16: {
                'item_name': 'Sugar Cloth Helmet',
                'img_coords': (16 * 5 * 3 - 5, 0, 16 * 3, 16 * 3),
                'stackable': False,
                'damage': 0,
                'protection': 2,
                'destroy_type': 'None',
                'throwable': False, 
                },
            17: {
                'item_name': 'Sugar Cloth Tunic',
                'img_coords': (16 * 5 * 3, 16 * 3 + 4, 16 * 3, 16 * 3),
                'stackable': False,
                'damage': 0,
                'destroy_type': 'None',
                'protection': 6,
                'throwable': False, 
                },
            18: {
                'item_name': 'Sugar Cloth Pants',
                'img_coords': (16 * 5 * 3, 16 * 2 * 3, 16 * 3, 16 * 3),
                'stackable': False,
                'damage': 0,
                'destroy_type': 'None',
                'protection': 4,
                'throwable': False, 
                },
            19: {
                'item_name': 'Sugar Cloth Boots',
                'img_coords': (16 * 5 * 3, 16 * 3 * 3, 16 * 3, 16 * 3),
                'stackable': False,
                'damage': 0,
                'destroy_type': 'None',
                'protection': 2,
                'throwable': False, 
                },
            20: {
                'item_name': 'Blue Gelatin',
                'img_coords': (16 * 6 * 3 - 2, 0 - 2, 16 * 3, 16 * 3),
                'stackable': False,
                'damage': 0,
                'destroy_type': 'None',
                'protection': 0,
                'throwable': True,
                },
            21: {
                'item_name': 'Red Gelatin',
                'img_coords': (16 * 6 * 3 - 2, 16 * 2 * 3 - 2, 16 * 3, 16 * 3),
                'stackable': False,
                'damage': 0,
                'destroy_type': 'None',
                'protection': 0,
                'throwable': True,
                },
            22: {
                'item_name': 'Green Gelatin',
                'img_coords': (16 * 6 * 3 - 2, 16 * 1 * 3 - 2, 16 * 3, 16 * 3),
                'stackable': False,
                'damage': 0,
                'destroy_type': 'None',
                'protection': 0,
                'throwable': True,
                },
            23: {
                'item_name': 'Yellow Gelatin',
                'img_coords': (16 * 6 * 3 - 2, 16 * 3 * 3 - 2, 16 * 3, 16 * 3),
                'stackable': False,
                'damage': 0,
                'destroy_type': 'None',
                'protection': 0,
                'throwable': True,
                },
           }

with open('C:/Users/zrobi/Documents/python scripts/food wars/V_1.1/game_files/item_data/item_data.json', "w") as file:
    json.dump(item_data, file) 
print('Saved!')               